# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 62bff9c942a5ba8c3359c0b4e84ac49064915d13633948ab46dabc52bf709125fc331f46da26d8da842912900b8013a3150a6647c3adc26b27441f017e35a8f2

test:
  secret_key_base: ff0a2332548c80e93cf3474880279c342766172a530ccdd7befb0d545bbc6db8cffa38487ed8910ab2ed6fe289bacb7a9aaffe311f6538dd149ec7b4ab18724e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
